v1:
	gcc -O2 main.c -o main -lm

v2:
	gcc -O3 main.c -o main -lm

v3:
	gcc -Ofast main.c -o main -lm

v4:
	clang -O2 main.c -o main -lm

v5:
	clang -O3 main.c -o main -lm

v6:
	clang -Ofast main.c -o main -lm
