v1:
	g++ -O2 --std=c++2a main.cpp -o main

v2:
	clang++ -O2 --std=c++2a main.cpp -o main

v3:
	g++ -O3 --std=c++2a main.cpp -o main

v4:
	clang++ -O3 --std=c++2a main.cpp -o main

strip:
	strip -s main

clean:
	rm main
