local function is_munchausen(number: integer, cache: [10]integer)
    local n = number
    local total = 0
    while n > 0 do
        total = total + cache[n % 10]
        if total > number then
            return false
        end
        n = n // 10
    end
    return total == number
end

local N = 440000000

local cache: [10]integer = { 0 }
for i = 1, 9 do
    cache[i] = i ^ i
end

for n = 0, N - 1 do
    if is_munchausen(n, cache) then
        print(n)
    end
end
